version: '3.8'
services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker-pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  postgres-admin:
    container_name: 'pg-admin'
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dcard123@dcard.com
      PGADMIN_DEFAULT_PASSWORD: dcard123
    ports:
      - "81:80"
    depends_on:
      - postgres
  redis:
    container_name: 'redis'
    image: redis
    command: redis-server --requirepass password
    environment:
      TZ: Asia/Taipei
    restart: always
    ports:
      - "6379:6379"
  redis-admin:
    container_name: redis-admin
    image: erikdubbelboer/phpredisadmin
    restart: always
    environment:
      REDIS_1_HOST: redis:6379
      REDIS_1_AUTH: password
    ports:
      - "82:80"
    depends_on:
      - redis    
  backend:
    container_name: 'url-shortener'
    image: 'url-shortener'
    build: ./
    ports:
      - "8083:8083"
    restart: always
    environment:
      REDIS_HOST: redis:6379
      DB_HOST: postgres
    depends_on:
      - postgres
      - redis